name: Test - E2E - Performance # e2e tests running against a k8s cluster

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
      - closed

env:
  PERF_DATA_FILE: perf_data.json
  E2E_UTILS: /hack/e2e/perf/scripts/utils.sh

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  build-operator:
    uses: ./.github/workflows/build-operator.yaml
    name: Build Operator Image
    secrets: inherit

  minikube:
    needs:
    - build-operator
    name: Run Performance Tests on Minikube
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: install yq
        run: sudo snap install yq

      - name: Download Helm Values Artifact
        uses: actions/download-artifact@v3
        with:
          name: helm-values

      - name: Start Minikube
        run: minikube start --addons default-storageclass,storage-provisioner --driver=docker

      - name: Install Uffizzi Cluster Operator
        id: prev
        run: |
          helm dep update ./chart
          helm upgrade --install --wait pr-${{ github.event.pull_request.number }} \
          ./chart -f helm-values.yaml

      # Identify comment to be updated
      - name: Find comment for Performance Overview
        uses: peter-evans/find-comment@v2
        id: find-comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: "github-actions[bot]"
          body-includes: Performance Overview
          direction: last

      # Create/Update comment with action deployment status
      - name: Create or Update Comment with Performance Overview
        id: notification
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ## Performance Overview

            :gear: Running performance tests on Minikube

          edit-mode: replace

      - name: Create PERF_DATA_FILE
        run: |
          # Ensure the file exists and initialize it as an empty array if not
          if [ ! -f "PERF_DATA_FILE" ]; then
          echo '[]' > "PERF_DATA_FILE"
          fi

      - name: Time taken to create UffizziClusters with different numbers of workers
        run: |
          for n_workers in $(seq 0 5 30); do
          
            yq -i '.concurrent = "$n_workers"' helm-values.yaml
            n_simultaneous_clusters=3
          
            # time taken to create n clusters simultaneously
            time=$(bash hack/e2e/perf/01-multicluster.sh $n_simultaneous_clusters)
            bash $E2E_UTILS update_json_with_workers_and_time $n_workers $time $PERF_DATA_FILE
          
            cat data.json
          done
#
#      - name: Set concurrent to 10
#        uses: mikefarah/yq@master
#        with:
#          cmd: yq -i '.concurrent = "10"' helm-values.yaml
#
#      - name: Time taken to create UffizziClusters with 10 workers
#        run: |
#          JSON_FILE="data.json"
#          helm upgrade --install --wait pr-${{ github.event.pull_request.number }} \
#          ./chart -f helm-values.yaml
#          time=$(bash hack/e2e/perf/01-multicluster.sh)
#          jq --argjson newEntry "{\"workers\": 10, \"time\": $time}" '. += [$newEntry]' "$JSON_FILE" > "tmp.$$" && mv "tmp.$$" "$JSON_FILE"
#
#          cat data.json

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install matplotlib

      - name: Create Graph
        run: python hack/e2e/perf/viz/generate_graph.py

      - name: Upload to Imgur
        id: upload_image
        uses: devicons/public-upload-to-imgur@v2.2.2
        with:
          path: ./performance_graph.png
          client_id: ${{ secrets.IMGUR_CLIENT_ID }}

      - name: Update Comment with Performance Overview
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: ${{ steps.notification.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ##  Performance Overview
            
            ![Graph](${{ fromJSON(steps.upload_image.outputs.imgur_urls)[0] }})
          edit-mode: replace
